version: '3.7'

services:
  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fops_bot_db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    tmpfs: /var/lib/postgresql/data

  fops_bot:
    image: fops_bot:$TAG
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: "top.secret.token"
    restart: "no"
    command: "true"
